Models/Entities/Quote.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace LabW12Quotes.Models.Entities
{
    public class Quote
    {
        public int Id { get; set; }
        public string TheQuote { get; set; }
        public string WhoSaidIt { get; set; }

    }
}

Models/ErrorViewModel.cs
using System;

namespace LabW12Quotes.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using LabW12Quotes.Models;
using LabW12Quotes.Services;

namespace LabW12Quotes.Controllers
{
    public class HomeController : Controller
    {
        private IQuotesRepository _quotes;

        public HomeController(IQuotesRepository quotes)
        {
            _quotes = quotes;
        }

        public IActionResult Index()
        {
            return View(_quotes.ReadAll());
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/QuoteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using LabW12Quotes.Models.Entities;
using LabW12Quotes.Services;
using Microsoft.AspNetCore.Mvc;

namespace LabW12Quotes.Controllers
{
    public class QuoteController : Controller
    {
        private IQuotesRepository _quotes;

        private static Random _r = new Random();

        public QuoteController(IQuotesRepository quotes)
        {
            _quotes = quotes;
        }

        public IActionResult Index()
        {
            return View(_quotes.ReadAll());
        }
        
        public IActionResult RandomQuote()
        {
            var quotes = _quotes.ReadAll().ToList();

            var quote = quotes.ElementAt(_r.Next(quotes.Count));
            return Json(new
            {
                quote.TheQuote,
                quote.WhoSaidIt
            });
        }

        private bool IsAjaxRequest()
        {
            return Request.Headers["X-Requested-With"] == "XMLHttpRequest";
        }

        [HttpPost]
        public IActionResult Create(Quote quote)
        {
            if (ModelState.IsValid)
            {
              
                _quotes.Create(quote);
                if (IsAjaxRequest())
                {
                    return Json("Ok");
                }
            }
            if (IsAjaxRequest())
            {
                return Json("Not Ok");
            }
            return RedirectToAction("Index", "Home");
        }
    }
}

Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Views/Home/Index.cshtml
@model IEnumerable<LabW12Quotes.Models.Entities.Quote>

@{
    ViewData["Title"] = "Quotes";
}

<h2>@ViewData["Title"]</h2>
<button id="createQuoteBtn" class="btn btn-primary btn-sm">Create New Quote</button>
<div id="createArea">
    <partial name="_createQuote" model="new Quote()" />
   
</div>

<h2 id="theQuote"></h2>
<h3 id="whoSaidIt"></h3>

@section scripts{
    <script src="~/js/homeIndex.js"></script>
}



@*@model IEnumerable<LabW12Quotes.Models.Entities.Quote>

    @{
        ViewData["Title"] = "Index";
    }

    <h2>Index</h2>

    <p>
        <a asp-action="Create">Create New</a>
    </p>
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Id)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.TheQuote)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.WhoSaidIt)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Id)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.TheQuote)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.WhoSaidIt)
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                        @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                        @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
                    </td>
                </tr>
            }
        </tbody>
    </table>*@

Views/Home/_createQuote.cshtml
@model LabW12Quotes.Models.Entities.Quote

<h4>Quote</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" asp-controller="Quote" id="submitQuoteCreate">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="TheQuote" class="control-label"></label>
                <input asp-for="TheQuote" class="form-control" />
                <span asp-validation-for="TheQuote" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="WhoSaidIt" class="control-label"></label>
                <input asp-for="WhoSaidIt" class="form-control" />
                <span asp-validation-for="WhoSaidIt" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input asp-action="Create" asp-controller="Quote" type="submit" value="Create" class="btn btn-default" />
                <button id="cancelQuoteCreate" class="btn btn-danger">Cancel</button>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Quote/Index.cshtml
@model IEnumerable<LabW12Quotes.Models.Entities.Quote>


<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TheQuote)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.WhoSaidIt)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TheQuote)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.WhoSaidIt)
            </td>
            
        </tr>
}
    </tbody>
</table>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LabW12Quotes</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">LabW12Quotes</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - LabW12Quotes</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>